### ISSUE TITLE
issue with certificate issuance

### ISSUE THREAD

**Issue by earrpodz** [Venafi/openstack-heat-plugin-venafi#25]
Connecting to venafi tpp via heat plugin fails for every request with:

stack_status_reason  | Resource CREATE failed: ClientBadData: resources.venafi_certificate: key_type should be instance of vcert.KeyType

**Comment by mr-tron** [comment]
Do you use ECDSA or RSA in your zone?

**Comment by mr-tron** [comment]
https://github.com/Venafi/openstack-heat-plugin-venafi/commit/9c2b54cceffcb82087ec0e5a1a5f79484ca6c9fe in branch `fixing-fixing-key-type`

**Comment by earrpodz** [comment]
Resolved with 9c2b54c. Thanks!
